import { Monster, Prisma, RarityType, Tile, TileType } from '@prisma/client';
import { getIdBson } from '../../bin/getIdBson';

export const undeadMonsters = {
  skeletonKnight: {
    name: 'a skeleton knight',
    id: null,
    health: 100,
    mana: 0,
    rarity: RarityType.COMMON,
    imageUrl: '/sprites/monsters/skeleton-knight.png',
    modifierId: null,
    modifier: {
      armor: 30,
      strength: 30,
      constitution: 40,
      dexterity: 20,
      evasion: 20,
      intelligence: 10,
      magicResistances: 20,
      minDamage: 10,
      maxDamage: 20,

      luck: null,
      maxHealth: null,
      maxMana: null,
      manaRegeneration: null,
      healthRegeneration: null,
      spellDamage: null,
      spellDamageCritPower: null,
      spellDamageCritChance: null,
      meleeDamage: null,
      meleeDamageCritPower: null,
      meleeDamageCritChance: null,
      duration: null,
    },
  },
  shade: {
    name: 'a shade',
    id: null,
    health: 50,
    mana: 0,
    rarity: RarityType.COMMON,
    imageUrl: '/sprites/monsters/shade.png',

    modifierId: null,
    modifier: {
      armor: 10,
      strength: 20,
      constitution: 20,
      dexterity: 40,
      evasion: 70,
      intelligence: 10,
      magicResistances: 40,
      minDamage: 6,
      maxDamage: 15,
      luck: null,
      maxHealth: null,
      maxMana: null,
      manaRegeneration: null,
      healthRegeneration: null,
      spellDamage: null,
      spellDamageCritPower: null,
      spellDamageCritChance: null,
      meleeDamage: null,
      meleeDamageCritPower: null,
      meleeDamageCritChance: 20,
      duration: null,
    },
  },
  skeletonHound: {
    name: 'a skeleton hound',
    id: null,
    health: 50,
    mana: 0,
    rarity: RarityType.COMMON,
    imageUrl: '/sprites/monsters/skeleton-hound.png',
    modifierId: null,
    modifier: {
      armor: 0,
      strength: 20,
      constitution: 30,
      dexterity: 20,
      evasion: 20,
      intelligence: 10,
      magicResistances: 10,
      minDamage: 4,
      maxDamage: 10,
      luck: null,
      maxHealth: null,
      maxMana: null,
      manaRegeneration: null,
      healthRegeneration: null,
      spellDamage: null,
      spellDamageCritPower: null,
      spellDamageCritChance: null,
      meleeDamage: null,
      meleeDamageCritPower: null,
      meleeDamageCritChance: null,
      duration: null,
    },
  },
  skeletonSpearman: {
    name: 'a skeleton spearman',
    id: null,
    health: 50,
    mana: 0,
    rarity: RarityType.COMMON,
    imageUrl: '/sprites/monsters/skeleton-spearman.png',
    modifierId: null,
    modifier: {
      armor: 20,
      strength: 20,
      constitution: 30,
      dexterity: 20,
      evasion: 20,
      intelligence: 10,
      magicResistances: 10,
      minDamage: 4,
      maxDamage: 10,
      luck: null,
      maxHealth: null,
      maxMana: null,
      manaRegeneration: null,
      healthRegeneration: null,
      spellDamage: null,
      spellDamageCritPower: null,
      spellDamageCritChance: null,
      meleeDamage: null,
      meleeDamageCritPower: null,
      meleeDamageCritChance: null,
      duration: null,
    },
  },
};
